language: haskell
ghc: 7.8
branches:
  only:
  - source
install:
  - cabal install hakyll blaze-html
before_script:
  - cd _site
  - git checkout master
  - git pull origin master
  - cd ..
script: cabal run -j build
after_script:
  - cd _site
  - git status
  - git add --all
  - git config --global user.email "michael.beidler@gmail.com"
  - git config --global user.name "Travis"
  - git commit -m "Built by Travis"
  - git push "$REPO_URL" master | grep -v http
  - cd ..
env:
  global:
  - secure: jD7ruLd0juuUK5FYIctGVqsHse1Jc7tC4FuNn/9AEqlLPXGzVtDL+pWRPkIrbBfmCx5Syi2udg6hKXLQKSCeGMDho2l66/BwqTHkXGqhztBBRLDfS1RiymNg+HASOvHS3pebhvz6Vt/PkFKdfkJ5JXFZYeGdBrBPa6xq4UX6vrM=
