language: haskell
ghc: 7.8
branches:
  only:
  - source
before_install:
  - git submodule foreach --recursive 'git checkout master; git ls-files | grep -v README.md | grep -v LICENSE | xargs -r git rm'
install:
  - cabal install hakyll pandoc-1.13.1 -fhttps
before_script:
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"
script: cabal run -j build
after_script:
  - cd _site
  - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
  - git remote add github https://${GH_TOKEN}@${REMOTE}
  - git add --all
  - git status
  - git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
  - git push github master:master | grep -v http
env:
  global:
  - secure: "ShnZHFYtaspqkK70MF27Td7fDvesggHZm8XUHSztXng60KslnizwoXOGgdVtj5YDLGmjCWSKkBWS1ua3UbCMfv/ZWuSHJ/wNB2PikfihH7CifIForTn58pNxjvmUB1x3LcMYSlKPmZDGSWrxlxCtIyy6CtIInWeXduKIhExW6WE="
